--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/AdminConfirmed/ArmourEffects
build-by-default: true
branches:
- master
projects:
  ArmourEffects:
    path: ""
    icon: icon.png
...
